name: CI Pipeline 
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      # checkout repo
      - name: checkout repository
        uses: actions/checkout@v4

      # installing python
      - name: setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # installing dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest streamlit

      # run tests
      - name: running tests
        run: PYTHONPATH=. pytest test/app_test.py 


